#!/usr/bin/env python3
"""Render the token-driven reference docs from their .tpl.md templates.

Covers strategist, executor, image-generator (LLM role prompts) plus the
preview-mode references skeleton and libraries — every doc that would otherwise
re-teach the agent stale theme literals (accent hex, font, chart palette).

Regenerated by init_theme.py every time theme-active.json changes. Hand edits
to the rendered files will be overwritten — edit the .tpl.md templates instead.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _token_render import load_theme, render  # noqa: E402

SKILL_ROOT = Path(__file__).resolve().parents[2] / "slide"
DEFAULT_THEME = SKILL_ROOT / "references" / "theme-active.json"

PAIRS = [
    ("references/strategist.tpl.md",      "references/strategist.md"),
    ("references/executor.tpl.md",        "references/executor.md"),
    ("references/image-generator.tpl.md", "references/image-generator.md"),
    ("references/skeleton.tpl.md",        "references/skeleton.md"),
    ("references/libraries.tpl.md",       "references/libraries.md"),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--theme", type=Path, default=DEFAULT_THEME)
    args = ap.parse_args()

    if not args.theme.exists():
        print(f"theme not found: {args.theme}", file=sys.stderr)
        return 2
    theme = load_theme(args.theme)

    for tpl_rel, out_rel in PAIRS:
        tpl_path = SKILL_ROOT / tpl_rel
        out_path = SKILL_ROOT / out_rel
        if not tpl_path.exists():
            print(f"template not found: {tpl_path}", file=sys.stderr)
            return 2
        try:
            rendered = render(tpl_path.read_text(encoding="utf-8"), theme)
        except (KeyError, ValueError) as e:
            print(f"render error in {tpl_path.name}: {e}", file=sys.stderr)
            return 1
        out_path.write_text(rendered, encoding="utf-8")
        print(f"wrote {out_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
