#!/usr/bin/env python3
"""Render anti-slop-theme.md from anti-slop-theme.tpl.md + theme-active.json.

Regenerated by init_theme.py every time theme-active.json changes. Hand edits
to anti-slop-theme.md will be overwritten — edit the template instead.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _token_render import load_theme, render  # noqa: E402

SKILL_ROOT = Path(__file__).resolve().parents[2] / "slide"
DEFAULT_TPL = SKILL_ROOT / "references" / "anti-slop-theme.tpl.md"
DEFAULT_OUT = SKILL_ROOT / "references" / "anti-slop-theme.md"
DEFAULT_THEME = SKILL_ROOT / "references" / "theme-active.json"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tpl", type=Path, default=DEFAULT_TPL)
    ap.add_argument("--theme", type=Path, default=DEFAULT_THEME)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    if not args.tpl.exists():
        print(f"template not found: {args.tpl}", file=sys.stderr)
        return 2
    if not args.theme.exists():
        print(f"theme not found: {args.theme}", file=sys.stderr)
        return 2

    tpl_text = args.tpl.read_text(encoding="utf-8")
    theme = load_theme(args.theme)

    try:
        rendered = render(tpl_text, theme)
    except (KeyError, ValueError) as e:
        print(f"render error: {e}", file=sys.stderr)
        return 1

    args.out.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
